module.exports = window.libWorldRequire = (path) ->
  switch path
    when 'lib/world/systems/action' then require('lib/world/systems/action')
    when 'lib/world/systems/collision' then require('lib/world/systems/collision')
    when 'lib/world/systems/movement' then require('lib/world/systems/movement')
    when 'lib/world/box2d' then require('lib/world/box2d')
    when 'lib/world/GoalManager' then require('lib/world/GoalManager')
    when 'lib/world/Grid' then require('lib/world/Grid')
    when 'lib/world/component' then require('lib/world/component')
    when 'lib/world/ellipse' then require('lib/world/ellipse')
    when 'lib/world/errors' then require('lib/world/errors')
    when 'lib/world/line_segment' then require('lib/world/line_segment')
    when 'lib/world/names' then require('lib/world/names')
    when 'lib/world/rand' then require('lib/world/rand')
    when 'lib/world/rectangle' then require('lib/world/rectangle')
    when 'lib/world/script_event_prereqs' then require('lib/world/script_event_prereqs')
    when 'lib/world/system' then require('lib/world/system')
    when 'lib/world/thang' then require('lib/world/thang')
    when 'lib/world/thang_state' then require('lib/world/thang_state')
    when 'lib/world/vector' then require('lib/world/vector')
    when 'lib/world/world' then require('lib/world/world')
    when 'lib/world/world_frame' then require('lib/world/world_frame')
    when 'lib/world/world_script_note' then require('lib/world/world_script_note')
    when 'lib/world/world_utils' then require('lib/world/world_utils')
    # debug systems
    when 'lib/debug/systems/Action' then require('lib/debug/systems/Action')
    when 'lib/debug/systems/AI' then require('lib/debug/systems/AI')
    when 'lib/debug/systems/Alliance' then require('lib/debug/systems/Alliance')
    when 'lib/debug/systems/Collision' then require('lib/debug/systems/Collision')
    when 'lib/debug/systems/Combat' then require('lib/debug/systems/Combat')
    when 'lib/debug/systems/Display' then require('lib/debug/systems/Display')
    when 'lib/debug/systems/Effect' then require('lib/debug/systems/Effect')
    when 'lib/debug/systems/Event' then require('lib/debug/systems/Event')
    when 'lib/debug/systems/Existence' then require('lib/debug/systems/Existence')
    when 'lib/debug/systems/Hearing' then require('lib/debug/systems/Hearing')
    when 'lib/debug/systems/Inventory' then require('lib/debug/systems/Inventory')
    when 'lib/debug/systems/Magic' then require('lib/debug/systems/Magic')
    when 'lib/debug/systems/Movement' then require('lib/debug/systems/Movement')
    when 'lib/debug/systems/Physics' then require('lib/debug/systems/Physics')
    when 'lib/debug/systems/Programming' then require('lib/debug/systems/Programming')
    when 'lib/debug/systems/Targeting' then require('lib/debug/systems/Targeting')
    when 'lib/debug/systems/UI' then require('lib/debug/systems/UI')
    when 'lib/debug/systems/Vision' then require('lib/debug/systems/Vision')
    when 'lib/debug/systems/Game' then require('lib/debug/systems/Game')
    # debug components
    # when 'lib/debug/components/XX' then require('lib/debug/components/XX')

    else throw new Error("Whoops, dunno what you're trying to load but I didn't include it in worldLoader")
